parse_config:
  raw_binding_map:
    '&sys_reset': Reset
    '&bootloader': Boot
    '&swapper': Win Next
    '&caps_word': Caps Wrd
    '&inv_qm': ¿

    '&kp LC(LG(LEFT))': Desk Left
    '&kp LC(LG(RIGHT))': Desk Right
    '&kp LC(TAB)': Tab Right
    '&kp LC(LS(TAB))': Tab Left
    '&kp LA(F4)': Win Close
    '&kp LC(F4)': Tab Close
    '&kp LS(TAB)': Win Prev
    '&kp LS(INS)': Paste

    '&out OUT_USB': Out USB
    '&out OUT_BLE': Out BLE

    '&bt BT_SEL 0': BT 1
    '&bt BT_SEL 1': BT 2
    '&bt BT_SEL 2': BT 3
    '&bt BT_SEL 3': BT 4
    '&bt BT_SEL 4': BT 5

    '&mmv MOVE_UP': M↑
    '&mmv MOVE_DOWN': M↓
    '&mmv MOVE_LEFT': M←
    '&mmv MOVE_RIGHT': M→

    '&msc SCRL_UP': MW↑
    '&msc SCRL_DOWN': MW↓
    '&msc SCRL_LEFT': MW←
    '&msc SCRL_RIGHT': MW→

    '&mkp LCLK': Left Click
    '&mkp RCLK': Right Click
    '&mkp MCLK': Middle Click
    '&mkp MB4': Back Click
    '&mkp MB5': Forward Click

  zmk_combos:
    combo_tab:    {align: top, o: 0.15}
    combo_del:    {align: top, o: 0.15}
    combo_capswd: {align: top}
    combo_f12:    {align: bottom}
    combo_btclr:  {align: bottom}

  zmk_keycode_map:
    # custom mappings
    C_VOL_UP: Vol Up
    C_VOL_DN: Vol Down
    C_AL_CALC: Calc
    C_PP: Play Pause

    LCTRL: Ctrl
    RCTRL: Ctrl
    LALT: Alt
    RALT: Alt
    LGUI: Gui
    RGUI: Gui
    LSHFT: Shift
    RSHFT: Shift
    ESC: Esc
    SPACE: ␣
    BSPC: ⌫
    RET: ⏎
    TAB: ↹
    DEL: ⌦

    PG_UP: Page Up
    PG_DN: Page Down
    INS: Insert
    HOME: Home
    END: End
    CAPS: Caps Lock
    PSCRN: Print Scrn
    PAUSE_BREAK: Pause Break

    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →

    C_PP: ⏯
    C_NEXT: ⏭️
    C_PREV: ⏮️

    # defaults
    AMPERSAND: '&'
    AMPS: '&'
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _
    BR_SQT GRAVE   : ‘'‘
    BR_N1   : ‘1’
    BR_N2    : ‘2’
    BR_N3    : ‘3’
    BR_N4    : ‘4’
    BR_N5    : ‘5’
    BR_N6   : ‘6’
    BR_N7   : ‘7’
    BR_N8   : ‘8’
    BR_N9   : ‘9’
    BR_N0   : ‘0’
    BR_MINUS  : ‘-’
    BR_EQUAL     : ‘=‘
    BR_Q       : ‘Q’
    BR_W   : ‘W’
    BR_E      : ‘E’
    BR_R      : ‘R’
    BR_T      : ‘T’
    BR_Y      : ‘Y’
    BR_U      : ‘U’
    BR_I     : ‘I’
    BR_O    : ‘O’
    BR_P     : ‘P’
    BR_ACUT  : ‘‘‘ 
    BR_LBKT  : ‘[‘
    BR_A     : ‘A’
    BR_S     : ‘S’
    BR_D     : ‘D’
    BR_F     : ‘F’
    BR_G     : ‘G’
    BR_H     : ‘H’
    BR_J     : ‘J’
    BR_K     : ‘K’
    BR_L     : ‘L’
    BR_CCED  : ‘Ç’
    BR_TILDE : ‘~’
    BR_RBKT  : ‘]’
    BR_BSLH  : ‘\’
    BR_Z     : ‘Z’
    BR_X     : ‘X’
    BR_C     : ‘C’
    BR_V     : ‘V’
    BR_B     : ‘B’
    BR_N     : ‘N’
    BR_M     : ‘M’
    BR_COMMA : ‘,’
    BR_DOT   : ‘.’ 
    BR_SEMI  : ‘;’
    BR_SLASH : ‘/’
    BR_KP_DOT: ‘.’
    BR_KP_COMMA   : ‘,’
    BR_DQT : ‘"‘
    BR_EXCL : ‘!’
    BR_AT     : ‘@’
    BR_HASH    : ‘#’
    BR_DLLR  : ‘$’
    BR_PRCNT : ‘%’
    BR_DIAE : ‘¨’ 
    BR_AMPS    : ‘&’
    BR_ASTRK    : ‘*’
    BR_LPAR    : ‘(‘
    BR_RPAR    : ‘)’
    BR_UNDER : ‘_’ 
    BR_PLUS : ‘+’
    BR_GRAVE  : ‘ `’ 
    BR_LBRC : ‘{‘
    BR_CIRC : ‘^’ 
    BR_RBRC  : ‘}’
    BR_PIPE  : ‘|’
    BR_LT : ‘<‘
    BR_GT   : ‘>‘
    BR_COLON : ‘:’
    BR_QMARK : ‘?’
    BR_SUP1    : ‘¹’
    BR_SUP2 : ‘²’
    BR_SUP3    : ‘³’
    BR_PND   : ‘£’
    BR_CENT : ‘¢’
    BR_NOT   : ‘¬’
    BR_SECT ALGR : ‘§’
    BR_DEG      : ‘°’
    BR_FORD  : ‘ª’
    BR_MORD: ‘º’
    BR_CRUZ : ‘₢’
    NUBS : ‘\’
    INT1 : ‘/’

    
