parse_config:
  raw_binding_map:
    '&sys_reset': Reset
    '&bootloader': Boot
    '&swapper': Win Next
    '&caps_word': Caps Wrd
    '&inv_qm': ¿

    '&kp LC(LG(LEFT))': Desk Left
    '&kp LC(LG(RIGHT))': Desk Right
    '&kp LC(TAB)': Tab Right
    '&kp LC(LS(TAB))': Tab Left
    '&kp LA(F4)': Win Close
    '&kp LC(F4)': Tab Close
    '&kp LS(TAB)': Win Prev
    '&kp LS(INS)': Paste

    "&bt BT_SEL 0":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 1
    "&bt BT_SEL 1":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 2
    "&bt BT_SEL 2":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 3
    "&bt BT_SEL 3":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 4
    "&bt BT_SEL 4":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 5
    "&out OUT_TOG":
      shifted: $$mdi:usb$$
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$

     BT_CLR: $$mdi:bluetooth-off$$
     BT_SEL: $$mdi:bluetooth-connect$$

    '&mmv MOVE_UP': M↑
    '&mmv MOVE_DOWN': M↓
    '&mmv MOVE_LEFT': M←
    '&mmv MOVE_RIGHT': M→

    '&msc SCRL_UP': MW↑
    '&msc SCRL_DOWN': MW↓
    '&msc SCRL_LEFT': MW←
    '&msc SCRL_RIGHT': MW→

    '&mkp LCLK': Left Click
    '&mkp RCLK': Right Click
    '&mkp MCLK': Middle Click
    '&mkp MB4': Back Click
    '&mkp MB5': Forward Click

  zmk_combos:
    combo_tab:    {align: top, o: 0.15}
    combo_del:    {align: top, o: 0.15}
    combo_capswd: {align: top}
    combo_f12:    {align: bottom}
    combo_btclr:  {align: bottom}

  zmk_keycode_map:
    # custom mappings
    C_VOL_UP:  $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$
    C_AL_CALC: Calc
    C_PP: Play Pause

    LCTRL: $$mdi:apple-keyboard-control$$
    RCTRL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    RALT: $$mdi:apple-keyboard-option$$
    LGUI: $$mdi:apple-keyboard-command$$
    RGUI: $$mdi:apple-keyboard-command$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    ESC:  $$mdi:keyboard-esc$$
    #SPACE: ␣
    SPACE: $$mdi:keyboard-space$$
    BSPC: ⌫
    RET: ⏎
    TAB: ↹
    DEL: ⌦
    ENTER: ⏎

    PG_UP: Page Up
    PG_DN: Page Down
    INS: Insert
    HOME: Home
    END: End
    CAPS: Caps Lock
    PSCRN: Print Scrn
    PAUSE_BREAK: Pause Break

     UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$

    C_PP: ⏯
    C_NEXT: ⏭️
    C_PREV: ⏮️

    # defaults
    AMPERSAND: '&'
    AMPS: '&'
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _
    BR_SQT GRAVE   : '
    BR_MINUS  : -
    BR_EQUAL     : =
  
    BR_ACUT  LBKT : ´
    BR_LBKT RBKT : [
   
    BR_CCED SEMI : Ç
    BR_TILDE SQT : ~
    BR_RBKT BSLH : ]
    BR_BSLH  NUBS  : \
  
    BR_COMMA  COMMA : ,
    BR_DOT  DOT : . 
    BR_SEMI SLASH : ;
    BR_SLASH INT1  : /
    BR_KP_DOT  KP_COMMA: .
    BR_KP_COMMA   KP_DOT  : ,
    
    BR_DQT LS(BR_SQT) : "
    BR_EXCL LS(BR_N1) : !
    BR_AT   LS(BR_N2)   : @
    BR_HASH  LS(BR_N3)  : #
    BR_DLLR LS(BR_N4)  : $
    BR_PRCNT LS(BR_N5) : %
    BR_DIAE LS(BR_N6) : ¨
    BR_AMPS   LS(BR_N7)  : &
    BR_ASTRK  LS(BR_N8)   : *
    BR_LPAR  LS(BR_N9)   : (
    BR_RPAR  LS(BR_N0)   : )
    BR_UNDER LS(BR_MINUS) : _
    BR_PLUS  LS(BR_EQUAL) : +
    BR_GRAVE LS(BR_ACUT) : `
    BR_LBRC  LS(BR_LBKT) : {
    BR_CIRC  LS(BR_TILDE) : ^
    BR_RBRC  LS(BR_RBKT)  : }
    BR_PIPE  LS(BR_BSLH)  : |
    BR_LT LS(BR_COMMA)  : <
    BR_GT LS(BR_DOT)   : >
    BR_COLON LS(BR_SEMI) : :
    BR_QMARK LS(BR_SLASH) : ?
